#!/usr/bin/env python3

import sys
import yaml

import rospy

from demo_interface import DemoInterface

def parse_joint_goal(filename):
    with open(filename) as f:
        return yaml.safe_load(f)

if __name__ == "__main__":
    d = DemoInterface()
    if sys.argv[0] == 'rosrun' and len(sys.argv) > 3:
        rospy.loginfo(f"Opening {sys.argv[3]}")
        joint_goal = parse_joint_goal(sys.argv[3])
    elif len(sys.argv) > 1:
        rospy.loginfo(f"Opening {sys.argv[1]}")
        joint_goal = parse_joint_goal(sys.argv[1])
    else:
        rospy.logerr("No joint goal provided, exiting")
        raise BaseException
    print(f"Joint goal: {joint_goal}")
    d.go_to_joint_goal(joint_goal)
