#!/usr/bin/env python3

from demo_interface import DemoInterface

def main():
  mover = DemoInterface()
  mover.set_planner_id("PRTRRTstarkConfigDefault")
  mover.plan_to_start()

if __name__ == '__main__':
  main()
