#!/usr/bin/env python3

import os
import sys
import yaml

import rospy
from sensor_msgs.msg import JointState

def save_joint_state(joint_state_msg, out_dir="./"):
    position = joint_state_msg.position
    next_file_name = get_next_file_name(out_dir)
    with open(os.path.join(out_dir, next_file_name), 'w') as out_file:
        yaml.safe_dump(position, out_file)

def get_next_file_name(directory):
    base_name = "joint_state"
    num = 1
    ext = ".yaml"
    name = base_name + '0' + str(num) + ext
    while os.path.exists(os.path.join(directory, name)):
        num += 1
        if num < 10:
            name = base_name + '0' + str(num) + ext
        else:
            name = base_name + str(num) + ext
    return name


if __name__ == "__main__":
    rospy.init_node("joint_goal_saver")
    joint_state_msg = rospy.wait_for_message("/joint_states", JointState)
    if len(sys.argv) > 1:
        out_dir = sys.argv[1]
        rospy.loginfo(f"Saving joint state file to {out_dir}")
        save_joint_state(joint_state_msg, out_dir)
    else:
        rospy.loginfo("No output directory specified, saving joint state file to cwd")
        save_joint_state(joint_state_msg)
